[mcp_servers.dokploy-mcp]
command = "/opt/homebrew/bin/dokploy-mcp"

[mcp_servers.dokploy-mcp.env]
DOKPLOY_URL = "https://dev.ahto.city/api"
DOKPLOY_API_KEY = "bo_dokfqaImrHsfPDvvnPzqbvxYhzWCQPBDNFBcDnAnYYlsQCnENGjNUhLmDVQioJhOOFw"
DOKPLOY_TIMEOUT = "60000"
